### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by vasilijajoksimovic** [alptium/vasilija.joksimovic#3]

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  I've done the task, you can review it now.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic,

I had previously reviewed @Tamaralb work.

To me the codebase looks nearly identical between you & Tamara, it seems like the two projects were copied between each other?

https://github.com/alptium/tamara.sevic/blob/master/calculator/src/calculator/racun.java
https://github.com/alptium/vasilija.joksimovic/blob/master/kalkulator/src/kalkulator/kalkulator.java

So since the code is the same, I am now copy-pasting the same comments I put for @Tamaralb which was:
1. Class name should start with a capital letter.
2. Class name should be in English.
3. There should be a space before and after an operator. Example "int firstNumber= sc.nextInt();" --> this should be "int firstNumber = sc.nextInt();" and similarly "result=firstNumber + secondNumber;" should be "result = firstNumber + secondNumber;"
4. The brackets are not correctly aligned, see examples here https://docs.oracle.com/javase/tutorial/java/nutsandbolts/if.html the section "class IfElseDemo" and try to fix.
5. Spelling is not correct, e.g. "Chooes" should be "Choose", and "seconde" should be "second"

**Comment by vasilijajoksimovic** [comment]
@valentinacupac I've redone the task, you may review it now...

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic here are the review comments:
1. The project name should be with lowercase, so it should be: calculator
2. You didn't add a package (similarly I saw in helloworld) you didn't add the package. 
3. Delete "// TODO Auto-generated method stub" because you've put code, so delete that line.
4. Inside the line "result  =firstNum" there should have been a space after the =, just like you had done for the other lines.
5. The alignment of the closing brackets "}" is not correct, perhaps see my example https://github.com/alptium/valentina.cupac/blob/master/calculator/src/org/alptium/valentinacupac/samples/calculator/Main.java
6. Please add the "try" block around the scanner, see from my example. This is important in case there's errors that the scanner can be released.

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  Redone

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic:
1. See https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comment 19.
2. See https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comment 18.
3. See https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comment  2.

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  Redone. I'm not sure what was the mistake about the name of  Java project - the third item, it's all lowercase and with no spaces.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, regarding project name, as can be seen below, it's spelt currently as Calculator but should be calculator. You changed only the folder name on disk, but not in Eclipse.

![image](https://user-images.githubusercontent.com/677159/35941775-b159660e-0c53-11e8-95e5-97a5adc5641f.png)

**Comment by vasilijajoksimovic** [comment]
Still, I'm not sure why does it appear as Calculator because in my eclipse
is also calculator. I didn't change folder name, I did the task again. Is
there any possibility  that the application remembers an earlier state?

07.02.2018. 22:11, "Valentina Cupać" <notifications@github.com> je
napisao/la:

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, I found out the reason, since before it was written in capitals, when I pulled the latest code it still stayed in capitals (this I think is due to windows). Then I cleared my folder and pulled again, and now it. Closing ticket.
