### ISSUE TITLE
Elite Sports Team Selector

### ISSUE THREAD

**Issue by vasilijajoksimovic** [alptium/vasilija.joksimovic#6]

**Comment by vasilijajoksimovic** [comment]
@valentinacupac You can check the task.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic see https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comment 14, 36.

Line 54 - why is there a space at start of the sentence?
Line 18 - why is this plural: Candidate candidates, why not just Candidate candidate?

Regarding "Do you want to enter the data for a new candidate? yes/no" what happens if I type in something that isn't yes or no, how will you handle it?

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  line 54,18- mistakes
I think I could implement something to handle with errors in general but  I've just done it in an simple way this time...
Not sure about comment 36...

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, looks fine. Next, I've added a new requirement for everyone, please add support for multiple candidates, use ArrayList and at the end show some statistics.

**Comment by vasilijajoksimovic** [comment]
@valentinacupac You can review it...

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, please see the fixes I have now pushed, you can see in the History tab. Let me know if the fixes I had done are clear, so that it can be helpful for the next homework.

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  I saw your changes, it's all clear. Thank you!

**Comment by valentinajemuovic** [comment]
Thanks @vasilijajoksimovic, closing ticket.
